
const guides = [
{slug:"van-57",title:"VAN 57 — Vanguard failed to initialize",cat:"Vanguard",summary:"Vanguard may not be starting correctly.",steps:["Restart Windows, then open League again.","Press Win + R, type services.msc, and check whether the vgc service is running. If stopped, set Startup type to Automatic and start it.","If the error persists, uninstall Riot Vanguard from Installed Apps, restart, launch League to reinstall it, then restart again.","If none of these work, collect Riot logs and contact Riot Support."],note:"Do not disable Windows security features to make Vanguard run."},
{slug:"van-68",title:"VAN 68 — Connection problem",cat:"Network",summary:"Riot Client may be having trouble communicating with Riot services.",steps:["Check Riot's service status and whether other players are affected.","Restart Riot Client and your PC.","Temporarily disconnect VPN or proxy services.","Restart your router and test another network if available.","If needed, open Command Prompt and run ipconfig /flushdns, then try again."]},
{slug:"van-1067",title:"VAN 1067 — Vanguard interruption",cat:"Vanguard",summary:"An unexpected Vanguard or system interruption may be involved.",steps:["Restart the computer and check Windows updates.","Open services.msc and confirm vgc is running.","Check Event Viewer → Windows Logs → System for errors at the exact time of the disconnect.","Temporarily close nonessential overlays and third-party monitoring tools.","Update chipset and firmware through the device manufacturer's official updater.","Submit Riot logs if the error continues."]},
{slug:"van-185",title:"VAN 185 — Client communication error",cat:"Network",summary:"The Riot Client may be losing communication with the game.",steps:["Completely exit League and Riot Client from the system tray and Task Manager.","Restart your computer.","Disable VPN or proxy services temporarily.","Test another connection if possible.","If it repeats every few games, record when it happens and send Riot Client logs to Riot Support."]},
{slug:"secure-boot",title:"Secure Boot and TPM checks",cat:"Windows",summary:"Learn how to inspect Windows security status without risky BIOS changes.",steps:["Press Win + R, type msinfo32, and inspect BIOS Mode and Secure Boot State.","Press Win + R, type tpm.msc, to view TPM status.","If Secure Boot is off and Vanguard explicitly requires it, consult your PC or motherboard manufacturer's instructions.","Before changing firmware settings, back up your BitLocker recovery key and verify your boot configuration."],note:"Never switch between Legacy/CSM and UEFI blindly; Windows may stop booting."},
{slug:"client-wont-open",title:"League Client won't launch",cat:"Client",summary:"Basic checks for a client that does not open.",steps:["Restart Windows and launch Riot Client normally.","Check Task Manager for stuck League or Riot processes; end them before retrying.","Check Windows updates and available Riot Client updates.","Try Riot's built-in repair options if available.","If it still fails, capture the error message and contact Riot Support."]},
{slug:"stuck-loading",title:"Stuck on loading screen",cat:"Client",summary:"A loading screen can hang because of local or connection problems.",steps:["Wait briefly to rule out a temporary load delay.","Check network connectivity and Riot's service status.","Close unnecessary background apps and restart the client.","Update graphics drivers from your PC or GPU manufacturer.","If it happens consistently, record whether it occurs before or after champion select."]},
{slug:"fps-drops",title:"Low FPS and stuttering",cat:"Performance",summary:"Improve stability before changing advanced system settings.",steps:["Check in-game video settings and reduce demanding options.","Close browser tabs, overlays, and heavy background applications.","Check power mode and temperatures, especially on laptops.","Update graphics drivers through official manufacturer channels.","Compare FPS in Practice Tool versus a live match to isolate the pattern."]},
{slug:"high-ping",title:"High ping or disconnects",cat:"Network",summary:"Find out whether your connection or Riot services are responsible.",steps:["Check Riot's service status.","Prefer Ethernet over Wi-Fi when possible.","Pause downloads and streaming on your network.","Restart your router and test another network.","Record when ping spikes occur and share details with your ISP or Riot Support."]},
{slug:"crash-mid-game",title:"Game crashes mid-match",cat:"Client",summary:"Collect evidence to distinguish graphics, Windows, and client issues.",steps:["Note the exact error and whether the client or whole PC closes.","Check Windows Reliability Monitor for crash reports.","Update Windows and graphics drivers.","Temporarily close overlays and other nonessential background programs.","Send crash logs to Riot Support if the problem repeats."]}
];
const $=s=>document.querySelector(s);
const search=$("#search"),results=$("#results"),filters=$("#filters"),empty=$("#empty");
let category="All";
const categories=["All","Vanguard","Client","Network","Performance","Windows"];
const discovered=new Set(JSON.parse(localStorage.getItem("hextechSecrets")||"[]"));
function unlock(id,message){if(discovered.has(id))return;discovered.add(id);localStorage.setItem("hextechSecrets",JSON.stringify([...discovered]));updateSecrets();toast("✧ Secret discovered — "+message);}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove("show"),3200);}
function updateSecrets(){$("#secretCount").textContent=`${discovered.size} / 5`;$("#secretSlots").innerHTML=Array.from({length:5},(_,i)=>`<span class="${discovered.has(i+1)?"found":""}">${discovered.has(i+1)?"✧":"?"}</span>`).join("");if(discovered.size===5)$("#secretModal .modal-inner h2").textContent="Keeper of the Archive";}
function render(){
const q=search.value.trim().toLowerCase();
filters.innerHTML=categories.map(c=>`<button class="filter ${category===c?"active":""}" data-category="${c}">${c}</button>`).join("");
const matches=guides.filter(g=>(category==="All"||g.cat===category)&&`${g.title} ${g.summary} ${g.steps.join(" ")}`.toLowerCase().includes(q));
$("#articleCount").textContent=`${matches.length} GUIDES`;
empty.hidden=matches.length>0;
results.innerHTML=matches.map(g=>`<article class="article guide" id="${g.slug}"><div class="article-header"><div class="article-meta"><span class="tag">${g.cat.toUpperCase()}</span><button class="copy-link share" data-share="${g.slug}" title="Copy direct link">↗ COPY LINK</button></div><h3>${g.title}</h3><p class="summary">${g.summary}</p></div><details class="guide-details" ${location.hash==="#"+g.slug?"open":""}><summary>VIEW TROUBLESHOOTING STEPS <span class="chevron">＋</span></summary><div class="answer"><h4>RECOMMENDED STEPS</h4><ol>${g.steps.map(s=>`<li>${s}</li>`).join("")}</ol>${g.note?`<p class="warning">⚠ ${g.note}</p>`:""}<a href="https://support-leagueoflegends.riotgames.com/" target="_blank" rel="noopener">OFFICIAL RIOT SUPPORT ↗</a></div></details></article>`).join("");
if(q==="666"||q==="veigar")unlock(3,"The Tiny Master of Evil");
}
filters.addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(b){category=b.dataset.category;render();}});
search.addEventListener("input",render);
results.addEventListener("click",e=>{const b=e.target.closest("[data-share]");if(b){const url=location.origin+location.pathname+"#"+b.dataset.share;navigator.clipboard?.writeText(url).then(()=>toast("Article link copied")).catch(()=>toast(url));}});
window.addEventListener("hashchange",()=>{render();const el=document.getElementById(location.hash.slice(1));if(el)el.scrollIntoView({behavior:"smooth"});});
document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement!==search){e.preventDefault();search.focus();}});
// Five subtle, optional secrets: logo taps, search keyword, footer symbol, Konami code, and five article opens.
let logoClicks=0;const brand=$(".brand")||$(".logo")||$("header a");
if(brand)brand.addEventListener("click",()=>{if(++logoClicks===5)unlock(1,"The Archivist's Greeting");});
$("#secrets").addEventListener("click",()=>{$("#secretModal").hidden=false;});
$("#closeModal").addEventListener("click",()=>{$("#secretModal").hidden=true;});
$("#secretModal").addEventListener("click",e=>{if(e.target.id==="secretModal")e.currentTarget.hidden=true;});
const footer=$(".footer-brand");if(footer)footer.addEventListener("click",()=>unlock(2,"A Poro in the Margins"));
const combo=["ArrowUp","ArrowUp","ArrowDown","ArrowDown","ArrowLeft","ArrowRight","ArrowLeft","ArrowRight","b","a"];let progress=0;
document.addEventListener("keydown",e=>{if(e.target.matches("input,textarea"))return;progress=e.key===combo[progress]?progress+1:e.key===combo[0]?1:0;if(progress===combo.length){unlock(4,"Cosmic Sequence");progress=0;document.body.classList.add("cosmic");setTimeout(()=>document.body.classList.remove("cosmic"),3500);}});
const opened=new Set();results.addEventListener("toggle",e=>{if(e.target.open){const a=e.target.closest(".guide");if(a){opened.add(a.id);if(opened.size>=5)unlock(5,"The Patient Researcher");}}},true);
$("#year").textContent=new Date().getFullYear();updateSecrets();render();
