
const guides = [
{slug:"van-57",title:"VAN 57 — Vanguard failed to initialize",cat:"Vanguard",summary:"Vanguard may not be starting correctly.",steps:["Restart Windows, then open League again.","Press Win + R, type services.msc, and check whether the vgc service is running. If stopped, set Startup type to Automatic and start it.","If the error persists, uninstall Riot Vanguard from Installed Apps, restart, launch League to reinstall it, then restart again.","If none of these work, collect Riot logs and contact Riot Support."],note:"Do not disable Windows security features to make Vanguard run."},
{slug:"van-68",title:"VAN 68 — Connection problem",cat:"Network",summary:"Riot Client may be having trouble communicating with Riot services.",steps:["Check Riot's service status and whether other players are affected.","Restart Riot Client and your PC.","Temporarily disconnect VPN or proxy services.","Restart your router and test another network if available.","If needed, open Command Prompt and run ipconfig /flushdns, then try again."]},
{slug:"van-1067",title:"VAN 1067 — Vanguard interruption",cat:"Vanguard",summary:"An unexpected Vanguard or system interruption may be involved.",steps:["Restart the computer and check Windows updates.","Open services.msc and confirm vgc is running.","Check Event Viewer → Windows Logs → System for errors at the exact time of the disconnect.","Temporarily close nonessential overlays and third-party monitoring tools.","Update chipset and firmware through the device manufacturer's official updater.","Submit Riot logs if the error continues."]},
{slug:"van-185",title:"VAN 185 — Client communication error",cat:"Network",summary:"The Riot Client may be losing communication with the game.",steps:["Completely exit League and Riot Client from the system tray and Task Manager.","Restart your computer.","Disable VPN or proxy services temporarily.","Test another connection if possible.","If it repeats every few games, record when it happens and send Riot Client logs to Riot Support."]},
{slug:"secure-boot",title:"Secure Boot and TPM checks",cat:"Windows",summary:"Learn how to inspect Windows security status without risky BIOS changes.",steps:["Press Win + R, type msinfo32, and inspect BIOS Mode and Secure Boot State.","Press Win + R, type tpm.msc, to view TPM status.","If Secure Boot is off and Vanguard explicitly requires it, consult your PC or motherboard manufacturer's instructions.","Before changing firmware settings, back up your BitLocker recovery key and verify your boot configuration."],note:"Never switch between Legacy/CSM and UEFI blindly; Windows may stop booting."},
{slug:"client-wont-open",title:"League Client won't launch",cat:"Client",summary:"Basic checks for a client that does not open.",steps:["Restart Windows and launch Riot Client normally.","Check Task Manager for stuck League or Riot processes; end them before retrying.","Check Windows updates and available Riot Client updates.","Try Riot's built-in repair options if available.","If it still fails, capture the error message and contact Riot Support."]},
{slug:"stuck-loading",title:"Stuck on loading screen",cat:"Client",summary:"A loading screen can hang because of local or connection problems.",steps:["Wait briefly to rule out a temporary load delay.","Check network connectivity and Riot's service status.","Close unnecessary background apps and restart the client.","Update graphics drivers from your PC or GPU manufacturer.","If it happens consistently, record whether it occurs before or after champion select."]},
{slug:"fps-drops",title:"Low FPS and stuttering",cat:"Performance",summary:"Improve stability before changing advanced system settings.",steps:["Check in-game video settings and reduce demanding options.","Close browser tabs, overlays, and heavy background applications.","Check power mode and temperatures, especially on laptops.","Update graphics drivers through official manufacturer channels.","Compare FPS in Practice Tool versus a live match to isolate the pattern."]},
{slug:"high-ping",title:"High ping or disconnects",cat:"Network",summary:"Find out whether your connection or Riot services are responsible.",steps:["Check Riot's service status.","Prefer Ethernet over Wi-Fi when possible.","Pause downloads and streaming on your network.","Restart your router and test another network.","Record when ping spikes occur and share details with your ISP or Riot Support."]},
{slug:"crash-mid-game",title:"Game crashes mid-match",cat:"Client",summary:"Collect evidence to distinguish graphics, Windows, and client issues.",steps:["Note the exact error and whether the client or whole PC closes.","Check Windows Reliability Monitor for crash reports.","Update Windows and graphics drivers.","Temporarily close overlays and other nonessential background programs.","Send crash logs to Riot Support if the problem repeats."]}
];
const $=s=>document.querySelector(s);
const search=$('#search'),results=$('#results'),filters=$('#filters'),empty=$('#empty');
const categories=['All','Vanguard','Client','Network','Performance','Windows'];
let category='All';
const KEY='hextechAdventureV2';
let state;
try{state=JSON.parse(localStorage.getItem(KEY))||{};}catch{state={};}
state.found=Array.isArray(state.found)?state.found.filter(n=>Number.isInteger(n)&&n>=1&&n<=6):[];
state.final=!!state.final;
state.gold=!!state.gold;
const found=new Set(state.found);
const data=[
{champ:'Scuttle Crab',name:'The River Wanderer',icon:'🦀',color:'#4ad6e7',clue:'A creature from the river has strayed into these halls. It never stays still for long.',hint:'Wait a few moments. Watch the edges of the page, then catch the visitor.',title:'The River Wanderer'},
{champ:'Veigar',name:'The Tiny Master',icon:'✦',color:'#a676f7',clue:'Small in stature, infinite in ambition. The master of evil awaits those who know his name.',hint:'The Archive search knows more than error codes. Search for the tiny master himself.',title:'The Tiny Master of Evil'},
{champ:'Viego',name:'The Ruined King’s Heart',icon:'💚',color:'#5cf3ad',clue:'A king lost everything for the one he loved. Four fragments remain where the Black Mist lingers.',hint:'A green crack has appeared near the About section. Restore the heart from its scattered fragments.',title:'The Ruined King’s Heart'},
{champ:'Pyke',name:'The Drowned List',icon:'☠',color:'#ef6376',clue:'The sea remembers every betrayal. Three names remain, written in blood and salt.',hint:'Find the red mark near the troubleshooting guides. Reveal and cross off three names.',title:'The Drowned List'},
{champ:'Ornn',name:'The Eternal Forge',icon:'⚒',color:'#ffad63',clue:'Even the greatest creations begin with raw materials. Only a worthy smith knows what comes first.',hint:'Look for an ember near the Archive’s footer. Heat the ore, strike the metal, then quench it.',title:'The Eternal Forge'},
{champ:'Graves',name:'The Bilgewater Heist',icon:'▤',color:'#e9c17e',clue:'One outlaw stole the gold, another stole the map. Somewhere in these halls lies a fortune never meant to be found.',hint:'Look for a wanted poster near the top of the page. The chest’s clue gives the order: sea, luck, gold.',title:'The Bilgewater Heist'}
];
function persist(){state.found=[...found].sort((a,b)=>a-b);localStorage.setItem(KEY,JSON.stringify(state));}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function openModal(id){$(id).hidden=false;document.body.classList.add('modal-open');}
function closeModal(id){$(id).hidden=true;if(!document.querySelector('.modal:not([hidden])'))document.body.classList.remove('modal-open');}
function reveal(n){const d=data[n-1],modal=$('#revealModal');$('#revealName').textContent=d.champ;$('#revealTitle').textContent=d.title+' · '+found.size+' / 6 discovered';$('#revealInner').style.setProperty('--reveal-color',d.color);const img=$('#revealPortrait');img.src=n===1?'':`https://ddragon.leagueoflegends.com/cdn/img/champion/loading/${d.champ.replace('The ','').split(' ')[0]}_0.jpg`;img.style.display=n===1?'none':'block';img.alt=d.champ+' champion artwork';img.onerror=()=>{img.style.display='none';};modal.classList.remove('animate');void modal.offsetWidth;modal.classList.add('animate');openModal('#revealModal');}
function unlock(n){if(found.has(n))return;found.add(n);persist();updateSecrets();reveal(n);if(n===1)$('#scuttle').hidden=true;}
function updateSecrets(){
$('#secretCount').textContent=found.size+' / 6';$('#secretSlots').innerHTML=data.map((d,i)=>`<span title="${found.has(i+1)?d.name:'Unknown'}" class="${found.has(i+1)?'found':''}">${found.has(i+1)?d.icon:'?'}</span>`).join('');
$('#riddles').innerHTML=data.map((d,i)=>`<div class="riddle"><div class="riddle-head"><span>${['I','II','III','IV','V','VI'][i]} · ${d.name}</span><span>${found.has(i+1)?'✧ DISCOVERED':'◇ UNKNOWN'}</span></div><p>“${d.clue}”</p><button class="hint-toggle" data-hint="${i}" aria-expanded="false">REVEAL HINT ↓</button><p class="hint-text" id="hint${i}" hidden>${d.hint}</p></div>`).join('');
$('#finalEntry').innerHTML=found.size===6?`<div class="final-call"><div class="eyebrow">✧ SIX SEALS BROKEN ✧</div><h3>${state.final?'The Seventh Legend':'The Forbidden Archive Awaits'}</h3><p>${state.final?'Your legend is written. Return to your chamber or view your reward.':'Something ancient has awakened beneath the Archive. A seventh chamber is now open.'}</p><button class="gold-btn" id="enterFinal">${state.final?'ENTER THE CHAMBER AGAIN':'ENTER THE FORBIDDEN ARCHIVE ↗'}</button></div>`:'';
document.body.classList.toggle('legendary',state.gold);
}
function render(){const q=search.value.trim().toLowerCase();filters.innerHTML=categories.map(c=>`<button class="filter ${category===c?'active':''}" data-category="${c}">${c}</button>`).join('');const matches=guides.filter(g=>(category==='All'||g.cat===category)&&`${g.title} ${g.summary} ${g.steps.join(' ')}`.toLowerCase().includes(q));$('#articleCount').textContent=matches.length+' GUIDES';empty.hidden=matches.length>0;results.innerHTML=matches.map(g=>`<article class="article guide" id="${g.slug}"><div class="article-header"><div class="article-meta"><span class="tag">${g.cat.toUpperCase()}</span><button class="copy-link share" data-share="${g.slug}" title="Copy direct link">↗ COPY LINK</button></div><h3>${g.title}</h3><p class="summary">${g.summary}</p></div><details class="guide-details" ${location.hash==='#'+g.slug?'open':''}><summary>VIEW TROUBLESHOOTING STEPS <span class="chevron">＋</span></summary><div class="answer"><h4>RECOMMENDED STEPS</h4><ol>${g.steps.map(s=>`<li>${s}</li>`).join('')}</ol>${g.note?`<p class="warning">⚠ ${g.note}</p>`:''}<a href="https://support-leagueoflegends.riotgames.com/" target="_blank" rel="noopener">OFFICIAL RIOT SUPPORT ↗</a></div></details></article>`).join('');if(q==='veigar'||q==='666')unlock(2);}
filters.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;render();}});search.addEventListener('input',render);
results.addEventListener('click',e=>{const b=e.target.closest('[data-share]');if(b){const url=location.origin+location.pathname+'#'+b.dataset.share;navigator.clipboard?.writeText(url).then(()=>toast('Article link copied')).catch(()=>toast(url));}});
window.addEventListener('hashchange',()=>{render();const el=document.getElementById(location.hash.slice(1));if(el)el.scrollIntoView({behavior:'smooth'});});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!document.querySelector('.modal:not([hidden])')){e.preventDefault();search.focus();}if(e.key==='Escape'){document.querySelectorAll('.modal:not([hidden])').forEach(m=>closeModal('#'+m.id));}});
$('#secrets').addEventListener('click',()=>openModal('#secretModal'));
$('#closeModal').addEventListener('click',()=>closeModal('#secretModal'));
$('#closePuzzle').addEventListener('click',()=>closeModal('#puzzleModal'));
$('#closeReveal').addEventListener('click',()=>closeReveal());
$('#revealContinue').addEventListener('click',()=>closeReveal());
$('#closeFinal').addEventListener('click',()=>closeModal('#finalModal'));
function closeReveal(){closeModal('#revealModal');if(found.size===6&&!state.final&&!state.finaleShown){state.finaleShown=true;persist();openModal('#secretModal');toast('✧ The Forbidden Archive is now open!');}}
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m){if(m.id==='revealModal')closeReveal();else closeModal('#'+m.id);}}));
$('#riddles').addEventListener('click',e=>{const b=e.target.closest('[data-hint]');if(!b)return;const hint=$('#hint'+b.dataset.hint);hint.hidden=!hint.hidden;b.textContent=hint.hidden?'REVEAL HINT ↓':'HIDE HINT ↑';b.setAttribute('aria-expanded',String(!hint.hidden));});
$('#finalEntry').addEventListener('click',e=>{if(e.target.closest('#enterFinal'))openFinal();});
$('#resetProgress').addEventListener('click',()=>{if(!confirm('Reset all six secrets, the Forbidden Archive, and your legendary theme? Your troubleshooting guides will not change.'))return;localStorage.removeItem(KEY);state={found:[],final:false,gold:false,finaleShown:false};found.clear();scuttleEscapes=0;$('#scuttle').hidden=true;updateSecrets();closeModal('#secretModal');setTimeout(showScuttle,1800);toast('Adventure reset. The secrets await you again.');});
// Scuttle runs twice on desktop; touch visitors can tap to catch.
const scuttle=$('#scuttle');let scuttleEscapes=0;
function moveScuttle(){const w=Math.max(90,innerWidth-95),h=Math.max(120,innerHeight-110);scuttle.style.left=(15+Math.random()*(w-15))+'px';scuttle.style.top=(15+Math.random()*(h-15))+'px';}
function showScuttle(){if(found.has(1))return;scuttle.hidden=false;moveScuttle();}
scuttle.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&scuttleEscapes<2){scuttleEscapes++;moveScuttle();}});
scuttle.addEventListener('click',()=>unlock(1));setTimeout(showScuttle,6500);
// Every champion has a distinct tactile puzzle.
function puzzle(n){$('#puzzleEyebrow').textContent=data[n-1].champ.toUpperCase()+' · HIDDEN CHALLENGE';$('#puzzleTitle').textContent=data[n-1].name;$('#puzzleStatus').textContent='';openModal('#puzzleModal');if(n===3)viego();if(n===4)pyke();if(n===5)ornn();if(n===6)graves();}
$('#viegoMark').addEventListener('click',()=>puzzle(3));$('#pykeMark').addEventListener('click',()=>puzzle(4));$('#ornnMark').addEventListener('click',()=>puzzle(5));$('#gravesMark').addEventListener('click',()=>puzzle(6));
function done(n){closeModal('#puzzleModal');unlock(n);}
function viego(){let next=0;const order=[2,0,3,1];$('#puzzleIntro').textContent='The Black Mist conceals a broken heart. Restore its four fragments in the correct order. Follow the faint numbers etched in each shard.';const area=$('#puzzleContent');area.innerHTML='<div class="heart-board" id="heartBoard"><div class="heart-target">♥</div></div><div class="fragment-row" id="fragmentRow"></div><p class="mini-caption">Tap the fragments in the order Ⅰ → Ⅱ → Ⅲ → Ⅳ to restore the heart.</p>';const row=$('#fragmentRow');[3,1,4,2].forEach(num=>{const b=document.createElement('button');b.className='heart-piece';b.textContent=['','Ⅰ','Ⅱ','Ⅲ','Ⅳ'][num]+' ✥';b.setAttribute('aria-label','Heart fragment '+num);b.onclick=()=>{if(num===next+1){next++;b.disabled=true;b.classList.add('placed');$('#heartBoard').style.setProperty('--heart-fill',next/4);$('#puzzleStatus').textContent=next+' / 4 fragments restored';if(next===4){$('#heartBoard').classList.add('restored');setTimeout(()=>done(3),900);}}else{$('#puzzleStatus').textContent='The mist rejects that fragment. Find '+['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][next]+'.';}};row.appendChild(b);});}
function pyke(){let count=0;const names=['THE CAPTAIN','THE BETRAYER','THE LAST WITNESS'];$('#puzzleIntro').textContent='A waterlogged list emerges. Reveal each name, then strike it from the list.';$('#puzzleContent').innerHTML=`<div class="pyke-list">${names.map((name,i)=>`<button class="pyke-name" data-name="${i}" data-stage="0"><span>▓▓▓▓▓▓▓▓▓▓▓▓</span><small>REVEAL NAME</small></button>`).join('')}</div><p class="mini-caption">Tap each line once to uncover the name, then again to cross it out.</p>`;$('#puzzleContent').onclick=e=>{const b=e.target.closest('[data-name]');if(!b)return;let stage=Number(b.dataset.stage);if(stage===0){b.querySelector('span').textContent=names[Number(b.dataset.name)];b.querySelector('small').textContent='CROSS OFF';b.dataset.stage='1';}else if(stage===1){b.classList.add('struck');b.querySelector('small').textContent='REMOVED';b.dataset.stage='2';count++;$('#puzzleStatus').textContent=count+' / 3 names crossed off';if(count===3)setTimeout(()=>done(4),850);}};}
function ornn(){let step=0;const stages=[['ORE','🔥 HEAT'],['HAMMER','⚒ STRIKE'],['WATER','💧 QUENCH']];$('#puzzleIntro').textContent='The forge needs three precise actions. Heat the ore, strike the metal, then quench the blade.';$('#puzzleContent').innerHTML='<div class="forge-anvil">⚒<div class="forge-fire">🔥</div></div><div class="forge-tools">'+stages.map((x,i)=>`<button data-forge="${i}" class="forge-tool">${x[1]}</button>`).join('')+'</div><p class="mini-caption">The order matters. An impatient smith must begin again.</p>';$('#puzzleContent').onclick=e=>{const b=e.target.closest('[data-forge]');if(!b)return;const i=Number(b.dataset.forge);if(i===step){step++;b.disabled=true;b.classList.add('used');$('#puzzleStatus').textContent=step+' / 3 forge actions';if(step===3){$('.forge-anvil').classList.add('forged');setTimeout(()=>done(5),1000);}}else{step=0;$('#puzzleContent').querySelectorAll('[data-forge]').forEach(x=>{x.disabled=false;x.classList.remove('used');});$('#puzzleStatus').textContent='A puff of smoke! The forge cools. Begin with heat.';}};}
function graves(){const symbols=['⚓','♠','◆','☠'];let dials=[0,0,0];const answer=[0,1,2];$('#puzzleIntro').textContent='Twisted Fate took the map. Graves kept the chest. Turn the three locks to the correct symbols.';$('#puzzleContent').innerHTML='<div class="treasure-chest"><div class="chest-lid">▰ BILGEWATER ▰</div><div class="chest-dials">'+dials.map((v,i)=>`<button class="chest-dial" data-dial="${i}" aria-label="Rotate dial ${i+1}">${symbols[v]}</button>`).join('')+'</div><div class="chest-key">The sea comes first, fortune follows, and the gem seals the deal.</div></div><button class="gold-btn" id="openChest">OPEN THE CHEST</button>';$('#puzzleContent').onclick=e=>{const dial=e.target.closest('[data-dial]');if(dial){const i=Number(dial.dataset.dial);dials[i]=(dials[i]+1)%4;dial.textContent=symbols[dials[i]];}if(e.target.closest('#openChest')){if(dials.every((x,i)=>x===answer[i])){$('.treasure-chest').classList.add('unlocked');$('#puzzleStatus').textContent='✦ JACKPOT! The Bilgewater fortune is yours.';setTimeout(()=>done(6),1200);}else{$('#puzzleStatus').textContent='The lock rattles. That combination is wrong.';$('.treasure-chest').classList.remove('shake');void $('.treasure-chest').offsetWidth;$('.treasure-chest').classList.add('shake');}}};}
// Final chamber: six sigils, ordered by the order of the original secrets.
let finalSequence=[];
function openFinal(){openModal('#finalModal');renderFinal();}
function renderFinal(){if(state.final){$('#finalHeading').textContent='The Seventh Legend';$('#finalIntro').textContent='You have conquered the Forbidden Archive. The gold-and-obsidian theme is yours.';$('#finalContent').innerHTML=`<div class="victory-emblem">✧</div><h3 class="legend-title">KEEPER OF THE ARCHIVE</h3><p>Six secrets discovered · Seventh chamber conquered</p><div class="reward-actions"><button id="themeToggle" class="gold-btn">${state.gold?'USE HEXTECH BLUE THEME':'USE LEGENDARY GOLD THEME'}</button><button id="saveCard" class="gold-btn">SAVE ACHIEVEMENT CARD</button></div><canvas id="achievementCanvas" width="960" height="540" hidden></canvas>`;$('#finalStatus').textContent='Achievement unlocked in this browser.';return;}
$('#finalHeading').textContent='Six seals. One final truth.';$('#finalIntro').textContent='Select the six champion sigils in the order they appear in the Archivist’s Ledger (I to VI).';$('#finalContent').innerHTML='<div class="final-core">✧</div><div class="final-progress">'+Array.from({length:6},(_,i)=>`<span>${i<finalSequence.length?data[finalSequence[i]-1].icon:'◇'}</span>`).join('')+'</div><div class="final-sigils">'+[4,6,2,5,1,3].map(n=>`<button class="final-sigil" data-sigil="${n}" ${finalSequence.includes(n)?'disabled':''} aria-label="${data[n-1].champ}">${data[n-1].icon}<small>${data[n-1].champ}</small></button>`).join('')+'</div><button id="clearSigils" class="subtle-btn">RESET SIGILS</button>';$('#finalStatus').textContent=finalSequence.length+' / 6 seals aligned';}
$('#finalContent').addEventListener('click',e=>{if(e.target.closest('#clearSigils')){finalSequence=[];renderFinal();return;}if(e.target.closest('#themeToggle')){state.gold=!state.gold;persist();updateSecrets();renderFinal();return;}if(e.target.closest('#saveCard')){saveCard();return;}const b=e.target.closest('[data-sigil]');if(!b)return;const n=Number(b.dataset.sigil);if(n!==finalSequence.length+1){$('#finalStatus').textContent='The seals resist. Follow the Ledger from I to VI.';$('.final-core').classList.add('shake');setTimeout(()=>$('.final-core').classList.remove('shake'),500);return;}finalSequence.push(n);renderFinal();if(finalSequence.length===6){$('#finalStatus').textContent='The Archive awakens…';$('.final-core').classList.add('awaken');setTimeout(()=>{state.final=true;state.gold=true;persist();updateSecrets();renderFinal();$('#finalModal').classList.add('victory');},1500);}});
function saveCard(){const c=$('#achievementCanvas'),ctx=c.getContext('2d');const grad=ctx.createLinearGradient(0,0,960,540);grad.addColorStop(0,'#050c13');grad.addColorStop(.55,'#192018');grad.addColorStop(1,'#0b1117');ctx.fillStyle=grad;ctx.fillRect(0,0,960,540);ctx.strokeStyle='#c8a568';ctx.lineWidth=5;ctx.strokeRect(24,24,912,492);ctx.textAlign='center';ctx.fillStyle='#e5c685';ctx.font='24px Georgia';ctx.fillText('✧ THE HEXTECH ARCHIVE ✧',480,94);ctx.font='bold 53px Georgia';ctx.fillText('KEEPER OF THE ARCHIVE',480,197);ctx.fillStyle='#e9e4d9';ctx.font='24px Arial';ctx.fillText('THE SEVENTH LEGEND',480,249);ctx.font='43px Arial';ctx.fillText('🦀  ✦  💚  ☠  ⚒  ◆',480,345);ctx.font='20px Arial';ctx.fillText('Six secrets discovered · Forbidden Archive conquered',480,413);ctx.fillStyle='#b7a27b';ctx.fillText(new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'}),480,463);const a=document.createElement('a');a.download='hextech-archive-seventh-legend.png';a.href=c.toDataURL('image/png');a.click();toast('Achievement card saved!');}
$('#year').textContent=new Date().getFullYear();updateSecrets();render();
// Place secret objects alongside the relevant sections without covering article text.
function positionMarks(){const positions=[['#gravesMark','.hero',.12],['#pykeMark','#guides',.1],['#viegoMark','#about',.12],['#ornnMark','footer',.12]];positions.forEach(([mark,section,fraction])=>{const el=$(mark),target=$(section);if(!el||!target)return;const r=target.getBoundingClientRect();el.style.top=Math.max(100,window.scrollY+r.top+Math.min(90,r.height*fraction))+'px';});}
window.addEventListener('resize',positionMarks);window.addEventListener('load',positionMarks);positionMarks();
